# Generated by Django 2.2 on 2020-06-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discountrule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(db_index=True, default=False)),
                ('coupon', models.CharField(max_length=50)),
                ('purchased_item_code', models.CharField(max_length=50)),
                ('min_purchased_item_required', models.IntegerField(default=1)),
                ('discounted_item_code', models.CharField(max_length=50)),
                ('discounted_price', models.FloatField(blank=True, null=True)),
                ('discount_percent', models.FloatField(blank=True, null=True)),
                ('discounted_item_limit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(db_index=True, default=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
